"""create alert actions table

Revision ID: dbd886323e25
Revises: 18a31445755e
Create Date: 2026-08-21 05:47:48.842101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd886323e25'
down_revision: Union[str, Sequence[str], None] = '18a31445755e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_actions_action'), 'alert_actions', ['action'], unique=False)
    op.create_index(op.f('ix_alert_actions_alert_id'), 'alert_actions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_actions_created_at'), 'alert_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_actions_id'), 'alert_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_actions_id'), table_name='alert_actions')
    op.drop_index(op.f('ix_alert_actions_created_at'), table_name='alert_actions')
    op.drop_index(op.f('ix_alert_actions_alert_id'), table_name='alert_actions')
    op.drop_index(op.f('ix_alert_actions_action'), table_name='alert_actions')
    op.drop_table('alert_actions')
    # ### end Alembic commands ###
